updated expand parameter doc to reflect actual use
opendatasoft/slate pull request #10
Opened 2017-08-29 12:58 UTC by jmorel

2017-09-22 13:08 UTC, meganelacheny approved these changes

2017-10-02 13:48 UTC, remilejeune requested changes
We should explain how to expand multiple parameters.
Is it with expand=user,group or expand=user&expand=group ?

2017-10-02 13:48 UTC, remilejeune commented on source/includes/_topics.md
> +curl http://yourdomain.opendatasoft.com/api/management/v2/datasets/da_XXXXX/security/users&expand=user
Should be a '?', not a '&'

2017-10-03 09:53 UTC, jmorel commented
@remilejeune I voluntarily removed multiple and nested expands because our current API didn't have any (at least at the time I wrote the doc)

2018-02-01 10:19 UTC, remilejeune approved these changes

2018-03-21 16:30 UTC, meganelacheny approved these changes

2018-03-21 16:30 UTC, merged