Updated changes
opendatasoft/slate pull request #2
Opened 2017-06-27 16:38 UTC by Aquassaut

Better words and sentences and descriptions and other things

2017-06-28 14:07 UTC, jmorel requested changes

2017-06-28 14:07 UTC, jmorel commented on source/includes/_changes.md
> +# Changes
Could you put Dataset Changes as a title to be in line with dataset metadata ?

2017-06-28 14:07 UTC, jmorel commented on source/includes/_changes.md
> +            "username": "delbingo"
not as neutral as we'd like :) Maybe johnsmith ?

2017-06-28 14:07 UTC, jmorel commented on source/includes/_changes.md
> +        "dataset": {
you didn't pass the expand parameter in the call, dataset should not be expanded.

2017-06-28 14:07 UTC, jmorel commented on source/includes/_changes.md
> +            "username": "delbingo"
You'd need to include the expand=user parameter in your call

2017-06-28 14:07 UTC, jmorel commented on source/includes/_changes.md
> +curl -XPUT https://yourdomain.opendatasoft.com/api/management/v2/restore_change/ \
missing space ? curl -X PUT ?

2017-06-28 14:43 UTC, Aquassaut commented on source/includes/_changes.md
> +        "dataset": {
It's not expanded, the domain is part of the key. It's the other instance that is wrong :-)

2017-06-28 14:44 UTC, Aquassaut commented on source/includes/_changes.md
> +            "username": "delbingo"
Why ? In this instance, the user is not expanded,

2017-06-28 14:45 UTC, Aquassaut commented on source/includes/_changes.md
> +curl -XPUT https://yourdomain.opendatasoft.com/api/management/v2/restore_change/ \
There's no need for a space and most people don't put it. It is the same for most dash-parameters in UNIX-like utilities.

2017-06-28 14:48 UTC, Aquassaut commented on source/includes/_changes.md
> +# Changes
:+1:

2017-06-28 14:48 UTC, Aquassaut commented on source/includes/_changes.md
> +            "username": "delbingo"
Obvious :+1: for johnsmith, BTW

2017-07-04 12:46 UTC, meganelacheny requested changes

2017-07-04 12:46 UTC, meganelacheny commented on source/includes/_changes.md
> +> An example change object
To ensure homogeneity in all examples, "An" should be deleted. Simply keep "Example change object".

2017-07-04 12:46 UTC, meganelacheny commented on source/includes/_changes.md
> +## Restore a changes
Shouldn't it be "Restore a change" or "Restore changes"?

2017-07-04 12:46 UTC, meganelacheny commented on source/includes/_changes.md
> +`change_uid` <br> *string* | identifier of the change to restore. This parameter must be sent in the json format, inside a json an object
"inside a json an object"? It does not makes sense to me.

2017-07-04 12:46 UTC, meganelacheny commented on source/includes/_changes.md
> +`change_uid` <br> *string* | unique identifier for the change
Also to ensure homogeneity in the documentation, could you please write the first letter of the first word of each description in capital letter?

2017-07-04 13:16 UTC, Aquassaut commented on source/includes/_changes.md
> +> An example change object
:+1:

2017-07-04 13:16 UTC, Aquassaut commented on source/includes/_changes.md
> +`change_uid` <br> *string* | unique identifier for the change
:+1:

2017-07-04 13:16 UTC, Aquassaut commented on source/includes/_changes.md
> +## Restore a changes
:+1:

2017-07-04 13:18 UTC, Aquassaut commented on source/includes/_changes.md
> +`change_uid` <br> *string* | identifier of the change to restore. This parameter must be sent in the json format, inside a json an object
Should be "a json object" indeed :+1:

2017-07-04 13:39 UTC, merged