Doc for metadata widget
opendatasoft/slate pull request #3
Opened 2017-07-03 13:27 UTC by remilejeune

2017-07-05 14:32 UTC, meganelacheny requested changes

2017-07-05 14:32 UTC, meganelacheny commented on source/includes/_form_widgets.md
>  `name` <br> *string* | Identifier for the object
"Identifier **of** the object"

2017-07-05 14:32 UTC, meganelacheny commented on source/includes/_form_widgets.md
>  `choices` <br> *array of strings* | *`choice` and `multichoice` only* List of all accepted values by the object, any other value will be rejected.
Could you add a line break after "*[...] only*"?
And the same goes for the other rows of this table!

2017-07-05 14:32 UTC, meganelacheny commented on source/includes/_form_widgets.md
>  `help_text` <br> *string* | Help text describing the constraints and uses of this form object
Writing in a description that "help_text" is a help text a little bit too obvious :)
"Informational text describing the constraints and uses of the form object", for example, could be a better description.

2017-07-05 14:32 UTC, meganelacheny commented on source/includes/_form_widgets.md
>  `orderable` <br> *boolean* | Flag indicated whether the visual component should allow values to be reordered or not
"Flag indicat**ing**"

2017-07-05 14:32 UTC, meganelacheny commented on source/includes/_form_widgets.md
> +`orderable` <br> *boolean* | Flag indicated whether the visual component should allow values to be reordered or not
"Flag indicat**ing**"

2017-07-05 14:32 UTC, meganelacheny commented on source/includes/_form_widgets.md
> +`orderable` <br> *boolean* | Flag indicated whether the visual component should allow values to be reordered or not
"Flag indicat**ing**"

2017-07-05 14:32 UTC, meganelacheny commented on source/includes/_form_widgets.md
> +The `toggle` widget is to be rendered as a ods-toggle input.
This introduction (as well as most of the others) could be improved. We need to make sure that everyone, no matter their "technical level", at least understands the introductions and descriptions.

2017-07-05 14:32 UTC, meganelacheny commented on source/includes/_form_widgets.md
> +        "type": "radio"
I think that's the example for the radio widget and not for the number widget.

2017-07-07 12:29 UTC, jmorel commented
[ch9710]

2017-07-20 15:03 UTC, jmorel commented
@nicoconstanzo I'm done with the doc, I'd like you to check the widgets examples and tell me if they are understandable.

2017-07-20 15:56 UTC, nicoconstanzo commented
@jmorel 
- Since you're suggesting the help_text as a parameter, why not use it in the first example to show the output?

- The `<select>` options are a bit criptic (I know they're licenses but still, something in the lines of Free, Personal, Professional?). In the object, I think it would be more clear putting the "widget" key before the "choices".
<img width="285" alt="screen shot 2017-07-20 at 17 48 24" src="https://user-images.githubusercontent.com/1652949/28426582-d9f5fcbe-6d73-11e7-9797-888915824d54.png">

 Wording: 
- *The `textinput` widget is to be rendered as a simple text input.*
 The **simple** word conveys that there's a complex option. Just saying text input should be enough. 
"is to be rendered" sounds contrived => will render, renders, outputs.
- Instead of **Example HTML widget** as the example title, why not use something like **Object HTML output**?

2017-07-21 07:46 UTC, jmorel commented
> Since you're suggesting the help_text as a parameter, why not use it in the first example to show the output?

You're right, I should use it. But in all examples.

> The <select> options are a bit criptic (I know they're licenses but still, something in the lines of Free, Personal, Professional?). In the object, I think it would be more clear putting the "widget" key before the "choices".

The only order that is relevant is the one we return in the platform. I should check out which it is. 
About the select options, you're right. I should either go for an example straight from the platform or a more symbolic one.

> Wording:

I'll update it. However I'll keep the "Example" as it is to stay in line with the rest of the wording of the right column (definition / example object / example request / example response)

2017-07-24 13:58 UTC, meganelacheny approved these changes

2017-07-25 14:31 UTC, merged