Dataset publish
opendatasoft/slate pull request #7
Opened 2017-07-24 15:53 UTC by remilejeune

2017-07-25 11:30 UTC, juliendbg requested changes
It's nice to have such a detailed doc about the state machine 👍

2017-07-25 11:30 UTC, juliendbg commented on source/includes/_dataset_actions.md
> +```HTTP
shouldn't it be `shell` or `bash` ?

2017-07-25 11:30 UTC, juliendbg commented on source/includes/_dataset_actions.md
> +```HTTP
same here

2017-07-25 11:30 UTC, juliendbg commented on source/includes/_dataset_actions.md
> +```HTTP
same

2017-07-25 11:30 UTC, juliendbg commented on source/includes/_dataset_actions.md
> +It will stopped the current processing job and let the processed records available in the search API.
-stopped +stop
-let +keep

2017-07-25 11:30 UTC, juliendbg commented on source/includes/_dataset_status.md
> +![Dataset states machine](dataset_status_states.png "Dataset states machine")
I'm surprised you can't go directly from deleting to idle without going through processing. Also, the transitions at the right end of the schema are mixed up, it's a little bit confusing.

2017-07-25 11:30 UTC, juliendbg commented on source/includes/_dataset_status.md
> +`since` <br> *datetime* | Timestamp writed the dataset entered in the current status
-writed +?

2017-07-25 11:30 UTC, juliendbg commented on source/includes/_dataset_status.md
> +The *idle* status means that the dataset does not performed a specific action. It can be published or not but no job is running. A newly created dataset is in that status.
-does not performed a specific action +is not currently involved in a processing ?

2017-07-25 11:30 UTC, juliendbg commented on source/includes/_dataset_status.md
> +The *limit_reached* status means that the dataset stop adding records because it reached the maximum of authorized records in the license.
-stop adding +stopped processing ?

2017-07-25 11:30 UTC, juliendbg commented on source/includes/_dataset_status.md
> +The *processing* status means that dataset's metadata or data (with the extraction, transformation ...) are made available to the search API.
-are made +are being made ?

2017-07-25 11:30 UTC, juliendbg commented on source/includes/_dataset_status.md
> +The *deleting* status means that the dataset's metadata and data are made unavailable from the search API.
-made unavailable +being removed ?

2017-07-25 11:30 UTC, juliendbg commented on source/includes/_dataset_status.md
> +The *aborting_processing* status means that the order to stop the processing has been received and the processing will stopped shortly
-will stopped +will stop (or will be stopped)

2017-07-25 11:30 UTC, juliendbg commented on source/includes/_datasets.md
> -`dataset_processing_status` <br> *[dataset processing status object](#dataset-processing-status)* <br> <em class="expandable">expandable</em> | Keyword indicating if the dataset is waiting to be publ
Did you remove all this on purpose ?

2017-07-25 11:30 UTC, juliendbg commented on source/includes/_datasets.md
> +This is an asynchronous call since the it may entail processing all records from the sources of the dataset.
-the

2017-07-25 11:30 UTC, juliendbg commented on source/includes/_datasets.md
> +It will stopped the current processing job and let the processed records available in the search API.
-stopped +stop
-let +keep

2017-07-25 16:10 UTC, meganelacheny requested changes

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_dataset_actions.md
> +A state of a dataset can be changed by triggering actions. An action can make the dataset available through the search API or remove it from the search API.
"**The** state of a dataset"

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_dataset_actions.md
> +A state of a dataset can be changed by triggering actions. An action can make the dataset available through the search API or remove it from the search API.
Also, what are the possible actions of a dataset ? It would be nice to have a list in this introduction before diving into the subject.

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_dataset_actions.md
> +This is an asynchronous call since the it may entail processing all records from the sources of the dataset.
"[...] since the it may entail processing all records [...]" What does that mean?
Also, this should be a description/an introduction for the section, which means that you should put this sentence right after the title of the section, before the examples.

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_dataset_actions.md
> +This will delete all currently indexed records for the dataset and make the dataset disappear from the explore catalog. Unpublishing a dataset does not delete the dataset, it merely acts on the expos
In my opinion, this is the introduction of **Unpublish a dataset**, so it should be before the examples, right after the title of the section.

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_dataset_actions.md
> +It will stopped the current processing job and let the processed records available in the search API.
I agree with @juliendbg 
Also, same as the previous comment, this is the explanation of the **Abort a dataset processing** section, meaning the introduction of that same section. You should put that right after the title, before the examples.

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_dataset_actions.md
> +It will create a version from the current data of the dataset.
Same, turn this into an introduction and put it right after the title.

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_dataset_status.md
> +A dataset status describe the current state of a dataset, if it's published or not and the running operation. It is a finite state machine, with the following properties:
"The dataset status describe**s** the current state of a dataset, **stating** if it's published or not, and the running operation."

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_dataset_status.md
> +* It is in a single state at a time
* a single state at a time

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_dataset_status.md
> +* The list of possible states is fully known
* the list of possible states, fully known

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_dataset_status.md
> +* The list of all transitions is fully known, each with the actions and conditions that can trigger them
* the list of all transitions, fully known, each with both the actions and conditions that can trigger them

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_dataset_status.md
> +Retrieves the current dataset status.
Again, this must be right after the title of the section.
And since this should be an introduction, it should be a proper one and not state the exact same thing as the title.

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_dataset_status.md
> +The *error* status means that the action failed. It can be an error from the source or a pipeline misconfiguration.
Again, this should be an introduction for this section.

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_dataset_status.md
> +`saving_version` | Version save failed
"Version sav**ing** failed"

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_dataset_status.md
> +The *limit_reached* status means that the dataset stop adding records because it reached the maximum of authorized records in the license.
Again, this should be the introduction/description of the section

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_dataset_status.md
> +The *deleting* status means that the dataset's metadata and data are made unavailable from the search API.
Also a description/introduction for the section

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_dataset_status.md
> +The *saving_version* status means that a new version of the dataset is being saved.
Introduction/Description for the section

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_datasets.md
> +This will delete all currently indexed records for the dataset and make the dataset disappear from the explore catalog. Unpublishing a dataset does not delete the dataset, it merely acts on the expos
Introduction/Description for the section

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_datasets.md
> +It will stopped the current processing job and let the processed records available in the search API.
Introduction/Description for the section

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_datasets.md
> +This is an asynchronous call since the it may entail processing all records from the sources of the dataset.
Introduction/Description for the section

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_datasets.md
> +It will create a version from the current data of the dataset.
Introduction/Description for the section

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_datasets.md
> +If the recover option is activated, it will recover all records.
Introduction/Description for the section

2017-07-25 16:10 UTC, meganelacheny commented on source/includes/_datasets.md
> +I will delete all recover data, without the possibility to cancel that action.
Introduction/Description for the section
Also, "I**t** will delete"

2017-07-26 12:39 UTC, remilejeune commented on source/includes/_dataset_status.md
> +`since` <br> *datetime* | Timestamp writed the dataset entered in the current status
gni ?

2017-07-26 12:46 UTC, remilejeune commented on source/includes/_dataset_actions.md
> +```HTTP
Maybe, but that's how we did in all the other parts of the doc.
It ends in under the shell tab.

I don't know why, but we may want to do a global refactoring.

2017-07-26 12:46 UTC, remilejeune commented on source/includes/_dataset_actions.md
> +```HTTP
⬆️

2017-07-26 12:46 UTC, remilejeune commented on source/includes/_dataset_actions.md
> +```HTTP
⬆️

2017-07-26 12:53 UTC, juliendbg commented on source/includes/_dataset_status.md
> +`since` <br> *datetime* | Timestamp writed the dataset entered in the current status
maybe you mean "when" instead of "writed"

2017-07-26 12:56 UTC, remilejeune commented on source/includes/_dataset_actions.md
> +It will stopped the current processing job and let the processed records available in the search API.
@meganelacheny the example are on the right when the doc is compiled. In the source we need to write them at the beginning of the section.

2017-07-26 12:58 UTC, remilejeune commented on source/includes/_dataset_status.md
> +The *idle* status means that the dataset does not performed a specific action. It can be published or not but no job is running. A newly created dataset is in that status.
It can any type of actions, no only processing. "is not currently involved in an action" is ok ?

2017-07-26 13:10 UTC, remilejeune commented on source/includes/_datasets.md
> -`dataset_processing_status` <br> *[dataset processing status object](#dataset-processing-status)* <br> <em class="expandable">expandable</em> | Keyword indicating if the dataset is waiting to be publ
Not really :)

2017-07-26 13:14 UTC, juliendbg commented on source/includes/_dataset_status.md
> +The *idle* status means that the dataset does not performed a specific action. It can be published or not but no job is running. A newly created dataset is in that status.
I guess yes

2017-07-26 13:29 UTC, remilejeune commented on source/includes/_dataset_actions.md
> +This is an asynchronous call since the it may entail processing all records from the sources of the dataset.
I change the sentence and remove the duplicated title/section name.

2017-07-26 13:29 UTC, remilejeune commented on source/includes/_dataset_actions.md
> +This will delete all currently indexed records for the dataset and make the dataset disappear from the explore catalog. Unpublishing a dataset does not delete the dataset, it merely acts on the expos
⬆️

2017-07-26 13:34 UTC, remilejeune commented on source/includes/_datasets.md
> +I will delete all recover data, without the possibility to cancel that action.
I deleted all the realtime status/actions :)

2017-07-26 13:36 UTC, remilejeune commented on source/includes/_dataset_status.md
> +![Dataset states machine](dataset_status_states.png "Dataset states machine")
You can, my drawing is just fucked up :)

2017-07-26 14:34 UTC, juliendbg approved these changes
A few typos but otherwise it's looking good

2017-07-26 14:34 UTC, juliendbg commented on source/includes/_dataset_actions.md
> +Remove the dataset from the serach API. Unpublishing a dataset does not delete the dataset.
-serach +search

2017-07-26 14:34 UTC, juliendbg commented on source/includes/_dataset_status.md
> +`published` <br> *boolean*       | True if the dataset is available in the search API.
You could remove the dot at the end, as Megane requested

2017-07-26 14:34 UTC, juliendbg commented on source/includes/_dataset_status.md
> +`published` <br> *boolean*       | True if the dataset is available in the search API.
You should remove the dot at the end of the line as Megane told us

2017-07-26 14:34 UTC, juliendbg commented on source/includes/_dataset_status.md
> +    "since": "2015-04-15T15:13:04+00:00"
missing comma

2017-07-26 14:34 UTC, juliendbg commented on source/includes/_dataset_status.md
> +The *limit_reached* status means that the dataset stop processing records because it reached the maximum of authorized records in the license.
the dataset **stopped** processing

2017-07-26 14:34 UTC, juliendbg commented on source/includes/_dataset_status.md
> +The *queue* status means that the action has been received and is waiting to be performed.
-queue +queued

2017-07-26 14:34 UTC, juliendbg commented on source/includes/_dataset_status.md
> +The *aborting_processing* status means that the order to stop the processing has been received and the processing will stopp shortly
-stopp +stop

2017-07-26 15:10 UTC, meganelacheny approved these changes

2017-07-26 15:42 UTC, juliendbg commented
👍

2017-07-26 15:45 UTC, merged