Add records errors section
opendatasoft/slate pull request #9
Opened 2017-08-01 14:21 UTC by remilejeune

2017-08-01 14:28 UTC, Aquassaut commented on source/includes/_dataset_status.md
>      "published": True,
true, not True

2017-08-01 14:28 UTC, Aquassaut commented on source/includes/_dataset_status.md
> +    "published": False,
false, not False

2017-08-01 14:28 UTC, Aquassaut commented on source/includes/_dataset_status.md
> +    "published": True,
true not True

2017-08-01 14:28 UTC, Aquassaut commented on source/includes/records_errors.md
> +The list of records errors object that applies to the given dataset. See [records errrors object](#records_errors) for specific attributes and the list of objects.
The list of record error objects that apply to the given dataset
In square brackets, there's a r too many to "errrors".

2017-08-08 14:44 UTC, meganelacheny requested changes

2017-08-08 14:44 UTC, meganelacheny commented on source/includes/_dataset_status.md
> +records_errors <br> *[records errrors object](#records_errors)* <br> <em class="expandable">expandable</em> | Errors which occurred during the processing. Can be from a processor, or a type conversio
"[records **errors** object]"

2017-08-08 14:44 UTC, meganelacheny commented on source/includes/_datasets.md
> +`default_security` <br> *object* |
Why is there no description for default security?

2017-08-08 14:44 UTC, meganelacheny commented on source/includes/records_errors.md
> +`record_id` <br> *string* | Id of the record after processing
Could you please replace "Id" by "Identifier"?

2017-08-08 14:44 UTC, meganelacheny commented on source/includes/records_errors.md
> +* a processor: when a value is valid or an operation failed
"when a value is **in**valid"

2017-08-08 14:44 UTC, meganelacheny commented on source/includes/records_errors.md
> +The record error describes errors which occured during the processing. An error comes from:
"which **occurred** during the processing"

2017-08-08 14:44 UTC, meganelacheny commented on source/includes/records_errors.md
> +`processor_uid` <br> *string* | Uid of the processor who generates the error
"**Unique identifier** of the processor **which** generates the error"

2017-08-08 14:44 UTC, meganelacheny commented on source/includes/records_errors.md
> +`field_uid` <br> *string* | Uid of the field involved in the error
Could you please replace "Uid" by "Unique identifier"?

2017-08-09 14:04 UTC, remilejeune commented on source/includes/_datasets.md
> +`default_security` <br> *object* |
This property should not be there ...

2017-08-09 14:12 UTC, remilejeune commented
I fixed the comments and deleted the save version part, it does not make sense to have a "save version" action but not api to list the versions and download them.
It will be dedicated development.

2017-08-10 15:10 UTC, meganelacheny approved these changes

2017-10-02 13:42 UTC, merged